# DigitalOcean App Platform Specification
# PRIVEE Quote Management System
name: privee-quote-system
region: nyc

# Global environment variables
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
    type: GENERAL

# Database service - PostgreSQL
databases:
  - engine: PG
    name: privee-db
    num_nodes: 1
    size: basic
    version: "15"

# Web service - Node.js application  
services:
  - name: privee-web
    source_dir: /
    github:
      repo: your-username/your-repo-name  # UPDATE THIS
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: node build-production.js
    
    # Runtime configuration
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Database environment variables
    envs:
      # Option 1: Using DATABASE_URL (recommended)
      - key: DATABASE_URL
        value: ${privee-db.DATABASE_URL}
        scope: RUN_TIME
        type: GENERAL
      
      # Option 2: Individual PostgreSQL variables (alternative to DATABASE_URL)
      # Uncomment these if you prefer individual variables instead of DATABASE_URL
      # - key: PGHOST
      #   value: ${privee-db.HOSTNAME}
      #   scope: RUN_TIME
      #   type: GENERAL
      # 
      # - key: PGUSER
      #   value: ${privee-db.USERNAME}
      #   scope: RUN_TIME
      #   type: GENERAL
      # 
      # - key: PGPASSWORD
      #   value: ${privee-db.PASSWORD}
      #   scope: RUN_TIME
      #   type: SECRET
      # 
      # - key: PGDATABASE
      #   value: ${privee-db.DATABASE}
      #   scope: RUN_TIME
      #   type: GENERAL
      # 
      # - key: PGPORT
      #   value: ${privee-db.PORT}
      #   scope: RUN_TIME
      #   type: GENERAL
        
    # Health check  
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 2
      
    # HTTP configuration
    http_port: 5000
    
    # Routes
    routes:
      - path: /
        preserve_path_prefix: true