# DigitalOcean App Platform Specification
# PRIVEE Quote Management System
name: privee-quote-system
region: nyc

# Database service - PostgreSQL
databases:
  - engine: PG
    name: privee-db
    num_nodes: 1
    size: basic
    version: "15"

# Web service - Node.js application  
services:
  - name: privee-web
    source_dir: /
    github:
      repo: your-username/your-repo-name  # UPDATE THIS
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: node build-production.js
    
    # Runtime configuration
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Environment variables
  envs:
       # Production environment setting
       - key: NODE_ENV
         value: production
         scope: RUN_TIME
         type: GENERAL

     services:
       - name: web
         envs:
           # Database connection string
           - key: DATABASE_URL
             value: ${db.DATABASE_URL}  # Bindable variable from DigitalOcean managed database
             scope: RUN_TIME
             type: GENERAL

           # Alternative: If using external PostgreSQL provider
           # - key: DATABASE_URL
           #   value: postgresql://username:password@host:port/database
           #   scope: RUN_TIME
           #   type: SECRET

     databases:
       - name: db
         engine: PG
         version: "15"  # PostgreSQL version
        
    # Health check  
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 2
      
    # HTTP configuration
    http_port: 8080
    
    # Routes
    routes:
      - path: /
        preserve_path_prefix: true