export const PRODUCTION_DATA = {
  adminUser: {
    username: "admin",
    password: "Admin2025!"
  },
  items: [
    {
      name: "Desayuno Club Plata Menú",
      description: "Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Papel, Personal y equipo de cocina,  Servicio de meseros (1 cada 10 personas, por 5 horas efectivas)",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "760.87",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Desayuno Club Plata Mobiliario",
      description: "Mesa redonda con mantelería fina,Sillas plegables,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "326.09",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Plata Menú",
      description: "Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Papel, Personal y equipo de cocina,  Servicio de meseros (1 cada 10 personas, por 5 horas efectivas)",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "762.00",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Plata Mobiliario",
      description: "Mesa redonda con mantelería fina,Sillas plegables,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "342.35",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Desayuno Gala Plata Menú",
      description: "Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Papel, Personal y equipo de cocina,  Servicio de meseros (1 cada 10 personas, por 5 horas efectivas)",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "375.91",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Desayuno Gala Plata Mobiliario",
      description: "Mesa redonda con mantelería fina,Sillas plegables,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "763.22",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Desayuno Club Oro Menú",
      description: "Cecina de Res con Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Lino, Personal y equipo de cocina,  Servicio de meseros (2 cada 10 personas, por 5 horas efectivas)",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "763.91",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Club Oro Decoración",
      description: "Menú personalizado (2 por mesa)",
      category: "Decoración",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "10.91",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Club Oro Mobiliario",
      description: "Mesa redonda con mantelería fina, Sillas Tiffany,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "316.48",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Oro Menú",
      description: "Cecina de Res con Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Lino, Personal y equipo de cocina,  Servicio de meseros (2 cada 10 personas, por 5 horas efectivas)",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "776.09",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Oro Decoración",
      description: "Menú personalizado (2 por mesa)",
      category: "Decoración",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "11.09",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Oro Mobiliario",
      description: "Mesa redonda con mantelería fina, Sillas Tiffany,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "321.52",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Gala Oro Menú",
      description: "Cecina de Res con Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Lino, Personal y equipo de cocina,  Servicio de meseros (2 cada 10 personas, por 5 horas efectivas)",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "785.22",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Gala Oro Decoración",
      description: "Menú personalizado (2 por mesa)",
      category: "Decoración",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "11.22",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Gala Oro Mobiliario",
      description: "Mesa redonda con mantelería fina, Sillas Tiffany,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "325.30",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Desayuno Club Platino Menú",
      description: "Bistek de Res con Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Lino, Personal y equipo de cocina,  Servicio de meseros (1 cada 10 personas, por 5 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "765.13",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Club Platino Decoración",
      description: "Menú personalizado (por invitado)",
      category: "Decoración",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "10.93",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Club Platino Mobiliario",
      description: "Mesa redonda con mantelería fina, Sillas Tiffany,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "316.98",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Platino Menú",
      description: "Bistek de Res con Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Lino, Personal y equipo de cocina,  Servicio de meseros (1 cada 10 personas, por 5 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "777.30",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Platino Decoración",
      description: "Menú personalizado (por invitado)",
      category: "Decoración",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "11.10",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Ceremonia Platino Mobiliario",
      description: "Mesa redonda con mantelería fina, Sillas Tiffany,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "322.03",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Gala Platino Menú",
      description: "Bistek de Res con Enchiladas o chilaquiles verdes o rojos acompañados de frijoles refritos, Fruta de temporada con queso cottage, miel y granola artesanal, Café americano (normal y descafeinado), Chocolate (leche deslactosada), Té verde, manzana canela y manzanilla, Pan mini dulce y salado, Servilletas de Lino, Personal y equipo de cocina,  Servicio de meseros (1 cada 10 personas, por 5 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "785.83",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Gala Platino Decoración",
      description: "Menú personalizado (por invitado)",
      category: "Decoración",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "11.23",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Desayuno Gala Platino Mobiliario",
      description: "Mesa redonda con mantelería fina, Sillas Tiffany,  Vajilla, cubiertos y cristalería (Acorde al menú), Plato base de diseño,",
      category: "Mobiliario",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "325.56",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Comida o Cena Club Plata Menú",
      description: "Menú 3 tiempos base de pollo o cerdo (A elegir) emplatado de 3 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 6 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas),",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "966.96",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Club Plata Mobiliario",
      description: "Mesas Club, con mantelería fina, Silla Plegable, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "205.48",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Club Plata Decoración",
      description: "Servilletas de papel, Centros de mesa bajos para mesa redonda con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "36.26",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Plata Menú",
      description: "Menú 3 tiempos base de pollo o cerdo (A elegir) emplatado de 3 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 6 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas),",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "949.57",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Plata Mobiliario",
      description: "Mesas Club, con mantelería fina, Silla Plegable, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "231.30",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Plata Decoración",
      description: "Servilletas de papel, Centros de mesa bajos para mesa redonda con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "36.52",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Plata Menú",
      description: "Menú 3 tiempos base de pollo o cerdo (A elegir) emplatado de 3 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 6 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas),",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "914.35",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Plata Mobiliario",
      description: "Mesas Club, con mantelería fina, Silla Plegable, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "268.21",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Plata Decoración",
      description: "Servilletas de papel, Centros de mesa bajos para mesa redonda con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "36.57",
      minMargin: 15,
      maxMargin: 25,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Oro Menú",
      description: "Menú 3 tiempos base de Pollo Cerdo o Res (a elegir) emplatado de 3 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 7 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Servicio de Café y Té, Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "972.04",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Oro Mobiliario",
      description: "Mesa redonda con mantelería fina (6) + Mesa de madera Rustica (4),  Sillas Crossback o Versalles + Tiffany con funda, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "221.48",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Oro Decoración",
      description: "Servilletas de Lino, Números de mesa (uno por mesa), Menú personalizado (dos por mesa), Centros de mesa bajos para mesa redonda + caminos para mesa rectangular con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "36.91",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Oro Menú",
      description: "Menú 3 tiempos base de Pollo Cerdo o Res (a elegir) emplatado de 3 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 7 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Servicio de Café y Té, Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "973.42",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Oro Mobiliario",
      description: "Mesa redonda con mantelería fina (6) + Mesa de madera Rustica (4),  Sillas Crossback o Versalles + Tiffany con funda, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "221.79",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Oro Decoración",
      description: "Servilletas de Lino, Números de mesa (uno por mesa), Menú personalizado (dos por mesa), Centros de mesa bajos para mesa redonda + caminos para mesa rectangular con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "36.97",
      minMargin: 15,
      maxMargin: 30,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Platino Menú",
      description: "Menú 3 tiempos base de Pollo, Cerdo, Res o Salmon (a elegir) emplatado de 4 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 7 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Tornafiesta para el 80% de los invitados (chilaquiles verdes o rojos), Servicio de Café y Té, Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "991.30",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Platino Mobiliario",
      description: "Mesa redonda con mantelería fina (6) + Mesa de viga personalizada (4) Silla Prada o Metric, Crossback,  Versalles o Tiffany con funda, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "161.09",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Comida o Cena Ceremonia Platino Decoración",
      description: "Servilletas de Lino, Números de mesa (uno por mesa), Menú personalizado (uno por comensal ), Centros de mesa bajos para mesa redonda + caminos para mesa rectangular con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "86.74",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Platino Menú",
      description: "Menú 3 tiempos base de Pollo, Cerdo, Res o Salmon (a elegir) emplatado de 4 tiempos incluye Pan, Barra de refrescos y hielos ilimitados por 7 horas (agua, agua mineral, coca cola, coca light, refresco de toronja, refresco de sabor,limones), Tornafiesta para el 80% de los invitados (chilaquiles verdes o rojos), Servicio de Café y Té, Personal y equipo de cocina, Servicio de meseros (1 cada 10 personas por 6 horas efectivas), Capitan de Meseros",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "992.70",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Platino Mobiliario",
      description: "Mesa redonda con mantelería fina (6) + Mesa de viga personalizada (4) Silla Prada o Metric, Crossback,  Versalles o Tiffany con funda, Vajilla y plaqué, Cristalería (vaso highball, copa tinto, old fashion y caballitos), Plato base de diseño",
      category: "Mobiliario",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "161.31",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Comida o Cena Gala Platino Decoración",
      description: "Servilletas de Lino, Números de mesa (uno por mesa), Menú personalizado (uno por comensal ), Centros de mesa bajos para mesa redonda + caminos para mesa rectangular con flor de temporada y follajes finos",
      category: "Decoración",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "86.86",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Club Plata Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "140.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Club Plata Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "140.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Ceremonia Plata Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "160.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Ceremonia Plata Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "160.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Gala Plata Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "180.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Gala Plata Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "180.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Club Oro Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "154.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Club Oro Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "154.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Ceremonia Oro Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "176.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Ceremonia Oro Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "176.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Gala Oro Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "198.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Gala Oro Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "198.00",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Club Platino Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "169.40",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Club Platino Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "169.40",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Ceremonia Platino Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "193.60",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Ceremonia Platino Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "193.60",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Cocteleria Gala Platino Menú",
      description: "Una hora de Servicio Cristalería apropiada y 3 variedades a elegir 3 variedades a elegir",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "217.80",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Canapes Gala Platino Menú",
      description: "Una hora de Servicio de bocadillos (5 Variedades a Elegir)",
      category: "Menú",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "217.80",
      minMargin: 15,
      maxMargin: 35,
      status: "active"
    },
    {
      name: "Audio y Video Club Plata DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE, Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Plata Pista",
      description: "Pista Iluminada Galaxy 4x4 m",
      category: "Audio y Video",
      quality: "Plata",
      ambientacion: "Club",
      basePrice: "54.18",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Plata DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Plata Pista",
      description: "Pista Iluminada Galaxy 4x4 m",
      category: "Audio y Video",
      quality: "Plata",
      ambientacion: "Ceremonia",
      basePrice: "54.18",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Plata DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Plata Pista 4x4",
      description: "Pista Iluminada Galaxy 4x4 m",
      category: "Audio y Video",
      quality: "Plata",
      ambientacion: "Gala",
      basePrice: "54.18",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Oro DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Oro Pista 5X5",
      description: "Pista Iluminada Galaxy 5x5 m",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "84.55",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Oro Pista 4X4 pers",
      description: "Pista personalizada impresa 4x4 m",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Club",
      basePrice: "87.27",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Oro DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Oro Pista 5x5",
      description: "Pista Iluminada Galaxy 5x5 m",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "84.55",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Oro Pista 4x4 Pers",
      description: "Pista personalizada impresa 4x4 m",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Ceremonia",
      basePrice: "87.27",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Oro DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Oro Pista 5x5",
      description: "Pista Iluminada Galaxy 5x5 m",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "84.55",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Oro pista 4x4 Pers",
      description: "Pista personalizada impresa 4x4 m",
      category: "Audio y Video",
      quality: "Oro",
      ambientacion: "Gala",
      basePrice: "87.27",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Platino DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Platino Pista 5x5",
      description: "Pista Iluminada Galaxy 5x5 m",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "87.27",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Club Platino Pista 5x5 pers",
      description: "Pista personalizada impresa 5x5 m",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Club",
      basePrice: "120.91",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Platino DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Platino Pista 5x5",
      description: "Pista Iluminada Galaxy 5x5 m",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "87.27",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Ceremonia Platino Pista 5x5 Pers",
      description: "Pista personalizada impresa 5x5 m",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Ceremonia",
      basePrice: "120.91",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Platino DJ",
      description: "Sonorización con sistemas de audio Profesional  hasta 130 personas Incluye: Servicio de DJ por 6 horas Audio profesional HK Mixer audio 12 canales Micrófono SHURE,Cabina 6 modulos LED",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "153.64",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Platino Pista 5x5",
      description: "Pista Iluminada Galaxy 5x5 m",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "87.27",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    },
    {
      name: "Audio y Video Gala Platino Pista 5x5 Pers",
      description: "Pista personalizada impresa 5x5 m",
      category: "Audio y Video",
      quality: "Platino",
      ambientacion: "Gala",
      basePrice: "120.91",
      minMargin: 15,
      maxMargin: 20,
      status: "active"
    }
  ]
};